name: Test Nanopub Publishing Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-workflow-nanopub-publish:
    uses: ./.github/workflows/yml2nanopub.yml
    with:
      ref: ${{ github.ref }}
      linkml_schema: https://raw.githubusercontent.com/eu-parc/parco-hbm/main/linkml/schema/peh.yaml
      data: data/example.yml
      changelog: data/_upcoming.yaml
      target_name: matrices
      dry_run: true  # Set to true for testing to avoid actual publishing
      output_htaccess: data/example-pairs.txt
      preflabel: label
      type_prefix: MA
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      NANOPUB_ORCID_ID: ${{ secrets.NANOPUB_ORCID_ID }}
      NANOPUB_NAME: ${{ secrets.NANOPUB_NAME }}
      NANOPUB_PRIVATE_KEY: ${{ secrets.NANOPUB_PRIVATE_KEY }}
      NANOPUB_PUBLIC_KEY: ${{ secrets.NANOPUB_PUBLIC_KEY }} 
      NANOPUB_INTRO_URI: ${{ secrets.NANOPUB_INTRO_URI }}
