name: Test Nanopub Publishing Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-workflow-nanopub-publish:
    uses: ./.github/workflows/yml2nanopub.yml
    with:
      ref: ${{ github.ref }}
      linkml_schema: schema/example.linkml.yml
      data: data/example.yml
      target_name: matrices
      server_mode: test
      parent_key: parent_matrix
      dry_run: true  # Set to true for testing to avoid actual publishing
      output: data/example-output.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      NANOPUB_ORCID_ID: ${{ secrets.NANOPUB_ORCID_ID }}
      NANOPUB_NAME: ${{ secrets.NANOPUB_NAME }}
      NANOPUB_PRIVATE_KEY: ${{ secrets.NANOPUB_PRIVATE_KEY }}
      NANOPUB_PUBLIC_KEY: ${{ secrets.NANOPUB_PUBLIC_KEY }}
      NANOPUB_INTRO_URI: ${{ secrets.NANOPUB_INTRO_URI }}
