name: Test Nanopub Publishing Workflow

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-workflow-nanopub-publish:
    uses: ./.github/workflows/yml2nanopub.yml
    with:
      ref: ${{ github.ref }}
      linkml_schema: https://raw.githubusercontent.com/eu-parc/parco-hbm/main/linkml/schema/peh.yaml
      data: data/example.yml
      changelog: data/_upcoming.yaml
      target_name: matrices
      dry_run: true  # Set to true for testing to avoid actual publishing
      output_htaccess: data/example-pairs.txt
      preflabel: label
      type_prefix: MA
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      NANOPUB_INTRO_URI: "https://w3id.org/np/RACq6O6F4gSuC0A037LXUt2QOr_yYHJUwx3wAWDGv4Ryc"
      NANOPUB_NAME: "Gertjan Bisschop"
      NANOPUB_ORCID_ID: "https://orcid.org/0000-0001-8327-0142"
      NANOPUB_PUBLIC_KEY: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArlLcAwjvZ4CcLJrgreOAZBEMWulAW3ja+oEceoowiWmR7sgGOKB0HdJIX2eA2FnoR4ZFaoSjLvszMs0+qfu1mVSQk/txEI6gbZME0A75nk8/IPh26+JnEVKOtaVM61F6HZ/sh/lbF8a8WOtf0FyBlfx3kn1jq7N7EdYGWYyFvLQf9YVIOcgz2X8mP7hWJ6p+UoCK7ZzmOBNELwd1NeQQe1Iwt4tbQR/CtjMYwZZTfDRVh6tCOv7jC3IywhiwVFmFp4mXN5f0/LjByzqQSVbxwAMWvhy41W9+eJJGUiLiumHOdY4Y/pwnHVyuPuiTfRn+GQsAaB+nOwpOkQSofpdvuwIDAQAB"
      NANOPUB_PRIVATE_KEY: ${{ secrets.NANOPUB_PRIVATE_KEY }}
